server:
    port: 9050

spring:
    application:
        name: ValidateBean

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        serviceUrl:
            defaultZone: http://localhost:9050/eureka/
